thrift: Autospec creation for update from version 0.16.0 to version 0.17.0
Aki Sukegawa (1):
      THRIFT-5536 Fix cross language tests

Alex Kormukhin (1):
      THRIFT-5519 Java async client loses exceptions in void methods

Andreas Krennmair (1):
      THRIFT-5569: add negative size checks in Go generator when reading maps, sets and lists

Andreas Renggli (1):
      Fixes #5529 missing space in between "<" and "::" in c++ generator

Blacker1230 (1):
      fix binary protocol's first byte value.

Christopher Friedt (1):
      THRIFT-5093: lib: cpp: test: clarify effect of MemoryPolicy on TMemoryBuffer

Christopher Tubbs (4):
      [CI] Appveyor - refresh pacman database on upgrade
      Fix merge bug (unconverted JUnit test)
      Trivial: Add missing AC_CHECK_HEADERS (#2610)
      Remove execute bit from plain text files in git (#2611)

Constantinos Dimitriou (1):
      Support for Python and enums

Dirk Sandbrink (1):
      [THRIFT-5510] On Windows NOMINMAX and WIN32_LEAN_AND_MEAN are unset even if set before

Finn Colman (1):
      Fix headers bug in Thrift/HttpClient.pm

Hernan Silberman (1):
      THRIFT-4086: Add missing calls to get_true_type when generating validator + metadata code

Jens Geyer (33):
      Release 0.16.0
      Updated changes.md for 0.16.0
      THRIFT-5504 CA2254 Message template should be compile time constant
      THRIFT-5505 error: 'close_generator' overrides a member function but is not marked 'override'
      THRIFT-5506 C26495 variable "t_field::req_" not initialized, t_field.h:40
      THRIFT-5504 CA2254 Message template should be compile time constant
      minor indent fixes
      FIX: test left too early on false premise
      THRIFT-5511 Full support for the new net6 "nullability" semantics
      THRIFT-5514 netstd test client slow in multithread mode
      Updated website update info, the ASF CMS is not longer used anymore.
      Updated website update info, the ASF CMS is not longer used anymore.
      FIX: incorrect URL in documentation
      THRIFT-5528 Incorrect HTML link for referenced typedefs
      FIX: remove duplicate constant decls
      THRIFT-5501 Remove Common Lisp support
      FIX: error C4244: conversion from "int64_t" to "int", possible data loss
      THRIFT-5540 Can't use a typedef for a container type containing enums in a constant
      Pass cancellation token to AcceptTcpClientAsync() in net6
      Revert SHA-1: 52d263e77c48bbf7cbabd03161107557d1e410b1
      THRIFT-5578 #nullable disable collides with C# lang versions < 8
      THRIFT-5585 net5.0 end of support May 2022
      THRIFT-5586 User-Agent header not conforming to RFC 7231
      THRIFT-5588 Remove slist/senum from IDL
      THRIFT-5589 Haxe compiler/runtime fixes
      FIX misc license headers
      THRIFT-5590 Haxe complex inits
      eplaced outdated TLS test keys
      script to regenerate server/client keys
      script to regenerate server/client keys
      Revert "Update thrift_socket_transport.erl"
      CHANGES.md updated
      fixing missing EXTRA_DISTs

Jeremiah (1):
      Fix winsock capitalization for case sensitive cross-compilation

Jiayu Liu (37):
      THRIFT-5526 to use "private_members" instead of "private-members" as a consistent param casing
      THRIFT-5525 use "reuse_objects" instead of "reuse-objects" as a consistent param casing
      add support for converting to java optional
      update to gradle 6.9, jdk 15, update findbugs
      json gen should indent while printing include strings
      THRIFT-5552 apply clang-format to java generator
      add interface generation
      THRIFT-5551: java generator to add @Override where possible
      THRIFT-5521: [java gen] use jdk8 option type in java generator code
      THRIFT-5563: fix deprecation and enable xlint for java library (#2575)
      change the java gen @SuppressWarnings location
      travis ci to use xenial as base image
      THRIFT-5562: remove gradle wrapper and use installed gradle 6.9
      THRIFT-5545: use gradle convention in organizing java project
      THRIFT-5548: add kotlin code gen
      add travis_wait for rebuidling docker image
      wait for 45 minutes
      use 45 min timeout
      use 40 min not 45 min
      THRIFT-5564: create a basic github action (#2592)
      THRIFT-5564: setup java and kotlin lib building (#2593)
      THRIFT-5544: annotations_as_metadata java code gen param (#2553)
      THRIFT-5560: use JUnit 5 for all Java lib tests (#2574)
      THRIFT-5567: remove cl namespace references (#2580)
      THRIFT-5570: update java lib document about gradle usage (#2583)
      THRIFT-5568: enforce consistent Java formatting (#2581)
      THRIFT-5571: add metadata map building to kotlin generator (#2584)
      THRIFT-5568: Add CI formatting/test checks for Java and Kotlin (#2599)
      THRIFT-5553: use newer gradle API (#2561)
      THRIFT-5543: add type parameter to java lib field metadata (#2552)
      THRIFT-5580: refactor kotlin cross tests (#2600)
      THRIFT-5564: setup cross test in GitHub action (#2602)
      THRIFT-5582: Improve TProtocol.java for Kotlin generator (#2603)
      THRIFT-5581: use gradle 7 for java/kotlin (#2601)
      THRIFT-5584: use gradle toolchain to specify Java 11 with --release 8 (#2606)
      THRIFT-5575: add a github workflow to invoke cmake (#2595)
      Pin integer-encoding to 3.0.3 (#2627)

Jonas Marty (1):
      Fixes #5500, uncompilable code when a .thirft struct named 'System' is present

Kevin Wojniak (7):
      init gen_enum_ to false
      clean up formatting
      fix broken syntax for old style enum
      match existing style for setting default value of gen_enum_
      don't output empty import line if old style enums are used
      add tests
      update makefile

Leon Scharnowski (1):
      workaround MSVC compiler bug

Michael Leinartas (1):
      THRIFT-5599: contrib/fb303 does not compile after C++ library refactorings

Michael Smith (1):
      THRIFT-5595: Handle peek request error with SSLSocket

Mike Cronce (1):
      lib/rs/Cargo.toml:  Update ordered-float

Márton Csordás (1):
      THRIFT-5467 Python: fix CannotSendHeader exception

Phil Price (1):
      (typescript): Fix invalid optional members and argument generation

PikachuHy (1):
      fix typo

Sylwester Lachiewicz (1):
      THRIFT-5502 Log SocketException at WARN level only + Fix formatting

Tamas Kovacs (1):
      THRIFT-5515: TConnection::workSocket reads all pending oneway requests.

TeinRnD (1):
      THRIFT-5499: Use blocking Read/Write calls to make sure the Receive/SendTimeout is checked.

TianMaiChengGhostRidder (2):
      Update thrift_socket_transport.erl
      If the amount of data transmitted is large, an error will be reported.

Triton Circonflexe (1):
      THRIFT-5592 Add uuid type documentation

Wu Jian Ping (1):
      Buffer.concat has performance issue

Yiyang Zhou (1):
      THRIFT-5449: Use poll instead of select in Python TNonblockingServer if available

Yuxuan 'fishy' Wang (17):
      Fix the travis issue
      Fix travis issue caused by 5f16344311
      THRIFT-5509: Close connection in IsOpen
      THRIFT-5509: Suppress noisy log from go's TSimpleServer
      THRIFT-5512: Update java dependencies
      THRIFT-5527: Don't swallow idl exceptions in Process function
      THRIFT-5539: Decouple TDuplicateToProtocol out of TDebugProtocol
      THRIFT-5541: Clarify on THeader key/value format in the spec
      Update Go versions used in travis and LANGUAGES.md
      THRIFT-5583: Add skip_remote arg to go compiler
      THRIFT-5569: Fix size check in TCompactProtocol.ReadListBegin
      Revert "THRIFT-5569: add negative size checks in Go generator when reading maps, sets and lists"
      Minor tweak to ErrAbandonRequest in go library
      THRIFT-5605: Client middleware to extract exceptions
      Update supported go version to 1.18.* and 1.19.*
      THRIFT-5609: Make TJSONProtocol safe to be used in deserializer pool
      Add a generic sync.Pool wrapper to go library

Zachary Kuhn (1):
      THRIFT-4100: Extract Rust read/write struct methods into a trait

dependabot[bot] (11):
      Bump async from 3.2.1 to 3.2.3 in /lib/js
      Bump cached-path-relative from 1.0.2 to 1.1.0 in /lib/ts
      Bump ansi-regex from 3.0.0 to 3.0.1
      Bump ajv from 6.5.4 to 6.12.6
      Bump minimist from 1.2.5 to 1.2.6 in /lib/js
      Bump minimist from 1.2.5 to 1.2.6 in /lib/ts
      Bump ajv from 6.7.0 to 6.12.6 in /lib/ts
      Bump cached-path-relative from 1.0.2 to 1.1.0 in /lib/js
      Bump grunt from 1.4.1 to 1.5.3 in /lib/ts
      Bump grunt from 1.4.1 to 1.5.3 in /lib/js
      Bump shell-quote from 1.7.2 to 1.7.3 in /lib/js

ihciah (1):
      fix wrong thrift strict header comparing

kashirin.alex (1):
      THRIFT-5576: fix old-style cast and redundant copy

konpeki622 (1):
      feat: support creating connection on OpenHarmonyOS

shangxu (1):
      fix Out Of Memory when use TNonblockingServer

tokcum (1):
      THRIFT-5283: add support for Unix Domain Sockets in lib/rs (#2545)

wangfan (1):
      THRIFT-5494 fix cpu full caused by infinite select() when frameSize < maxReadBufferBytes but readBufferBytesAllocated.get() + frameSize always greater than MAX_READ_BUFFER_BYTES

くらげ (1):
      Fixed proxy related bugs

郑桐 (1):
      THRIFT-5495: close client when shutdown server in go lib